app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();
Route::resource('order', 'OrderController');
Route::resource('good', 'GoodController');
Route::get('/home', 'HomeController@index');

app/Advert.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class Advert extends Authenticatable
{
	public $timestamps = false;
    protected $primaryKey = 'user_id';

    protected $fillable = [
        'user_first_name', 'user_last_name', 'user_login',
    ];
    protected $hidden = [
        'user_password', 'remember_token',
    ];
    public function getAuthPassword()
    {
        return $this->user_password;
    }
    public function goods()
    {
        return $this->hasMany('App\Good','good_advert','good_id');
    }

}

app/Good.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Good extends Model
{
	public $timestamps = false;
    protected $primaryKey = 'good_id';
    public function advert()
    {
        return $this->belongsTo('App\Advert', 'good_advert', 'user_id');
    }
    public function orders()
    {
        return $this->hasMany('App\Order', 'order_good', 'good_id');
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	protected $primaryKey = 'order_id';
    public function setUpdatedAtAttribute($value)
	{
		//
	}
	
	const CREATED_AT = 'order_add_time';

	public function good()
    {
        return $this->belongsTo('App\Good', 'order_good', 'good_id');
    }
    public function state()
    {
        return $this->belongsTo('App\State', 'order_state', 'state_id');
    }
}

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    public $timestamps = false;
    protected $primaryKey = 'state_id';
    public function orders()
    {
        return $this->hasMany('App\Order', 'order_state', 'state_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GoodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Good;
use App\Advert;
use Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
class GoodController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
	public function index(Request $request)
    {
    	if(Input::has("paginate")) {
    		$paginate = Input::get("paginate");
    	} else{
    		$paginate= 2;
    	}
    	if(Input::has("order_by_name")) {
    		$order_by_name = Input::get("order_by_name");
    	} else{
    		$order_by_name = 'good_id';
    	}
    	if(Input::has("order_by_direstion")) {
    		$order_by_direction = Input::get("order_by_direstion");
    	} else{
    		$order_by_direction = 'asc';
    	}
        $goods=Good::orderBy($order_by_name, $order_by_direction)->paginate($paginate);;
        if ($request->ajax())
        {
            return view('ajax.goods', ['goods' => $goods]);
        }else{
            return view('goods', ['goods' => $goods]);
        }
    }
    public function edit($id)
    {	
    	$adverts=Advert::get();
    	$good=Good::find($id);
    	return view('editGood', ['good' => $good,'adverts'=>$adverts]);
    }
    public function update($id)
    {	
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = array(
            'good_advert'       => 'required',
            'good_name'      => 'required',
            'good_price' => 'required|numeric'
        );
        $validator = Validator::make(Input::all(), $rules);

        if ($validator->fails()) {
            return Redirect::to('good/' . $id . '/edit')
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        } else {
            // store
            $good = Good::find($id);
            $good->good_advert       = Input::get('good_advert');
            $good->good_name      = Input::get('good_name');
            $good->good_price = Input::get('good_price');
            $good->save();

            // redirect
            return Redirect::to('good');
        }
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UserFormRequest;
use App\Http\Requests;
use App\Order;
use App\State;
use Illuminate\Support\Facades\Input;

class OrderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {	
    	if(Input::has("paginate")) {
    		$paginate = Input::get("paginate");
    	} else{
    		$paginate= 2;
    	}
    	if(Input::has("order_by_name")) {
    		$order_by_name = Input::get("order_by_name");
    	} else{
    		$order_by_name = 'order_id';
    	}
    	if(Input::has("order_by_direstion")) {
    		$order_by_direction = Input::get("order_by_direstion");
    	} else{
    		$order_by_direction = 'asc';
    	}
        $orders=Order::orderBy($order_by_name, $order_by_direction);
        
        if(Input::has("order_state")) {
            $orders=$orders->where('order_state','=',Input::get("order_state"));
        }
        if(Input::has("date_from")) {
            $orders=$orders->whereDate('order_add_time','>=',Input::get("date_from"));
        }
        if(Input::has("date_to")) {
            $orders=$orders->whereDate('order_add_time','<=',Input::get("date_to"));
        }
        if(Input::has("order_client_phone")) {
            $orders=$orders->where('order_client_phone','like',Input::get("order_client_phone").'%');
        }
        if(Input::has("find")) {
            $orders=$orders->where('order_client_phone','like',Input::get("find").'%')->orWhere('order_client_name','like',Input::get("find").'%');
        }
        if(Input::has("order_good")) {
            $order_good=Input::get("order_good");
            $orders=$orders->whereHas('good', function($q) use ($order_good)
            {
                $q->where('good_name', 'like', $order_good.'%');

            });
        }
        if(Input::has("order_id")) {
            $orders=$orders->where('order_id','=',Input::get("order_id"));
        }
        $orders=$orders->paginate($paginate);
        if ($request->ajax())
        {
            return view('ajax.orders', ['orders' => $orders]);
        }else{
            $states=State::get();
            return view('orders', ['orders' => $orders,'states'=>$states]);
        }
    }
}

resources/views/ajax/goods.blade.php
	            	<table class="table">
					  <thead>
					    <tr>
					    	<th></th>
					      	<th data-order-name="good_id" data-order-direction="asc">#<i class="fa fa-sort active" aria-hidden="true"></i></th>
					      	<th data-order-name="good_name" data-order-direction="asc">Название<i class="fa fa-sort" aria-hidden="true"></i></th>
					      	<th data-order-name="order_client_phone" data-order-direction="asc">Цена<i class="fa fa-sort" aria-hidden="true"></i></th>
					      	<th data-order-name="order_good" data-order-direction="asc">Рекламодатель<i class="fa fa-sort" aria-hidden="true"></i></th>
					    </tr>
					  </thead>
					  <tbody>
						  @foreach ($goods as $index=>$good)
						    <tr>
						    	<td><input name ="good_select[]" type="checkbox" value="{{$good->good_id}}"></td>
						      	<td scope="row">{{$index+1}}</td>
						      	<td><a href="{{ route('good.edit', $good->good_id) }}">{{$good->good_name}}</a> <br> Внешний ID:{{$good->good_id}}</td>
						      	<td>{{$good->good_price}}</td>
						      	<td>{{$good->advert->user_first_name}} {{$good->advert->user_last_name}}<br>{{$good->advert->user_login}})</td>
						    </tr>
						   @endforeach
					  </tbody>
					</table>
					{!! $goods->render() !!}

resources/views/ajax/orders.blade.php
					<table class="table">
					  <thead>
					    <tr>
					      <th data-order-name="order_id" data-order-direction="asc">#<i class="fa fa-sort active" aria-hidden="true"></i></th>
					      <th data-order-name="order_client_name" data-order-direction="asc">Клиент<i class="fa fa-sort" aria-hidden="true"></i></th>
					      <th data-order-name="order_client_phone" data-order-direction="asc">Телефон<i class="fa fa-sort" aria-hidden="true"></i></th>
					      <th data-order-name="order_good" data-order-direction="asc">Товар<i class="fa fa-sort" aria-hidden="true"></i></th>
					      <th data-order-name="order_state" data-order-direction="asc">Статус<i class="fa fa-sort" aria-hidden="true"></i></th>
					    </tr>
					  </thead>
					  <tbody>
						  @foreach ($orders as $order)
						    <tr>
						      <td>{{$order->order_id}}</td>
						      <td>{{$order->order_client_name}}</td>
						      <td>{{$order->order_client_phone}}</td>
						      <td>{{$order->good->good_name}}<br>{{$order->good->advert->user_first_name}} {{$order->good->advert->user_last_name}} ({{$order->good->advert->user_login}})</td>
						      <td>{{$order->state->state_name}}</td>
						    </tr>
						   @endforeach
					  </tbody>
					</table>
					{!! $orders->render() !!}

resources/views/editGood.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
				<form method="POST" action="{{ route('good.update', $good->good_id) }}" accept-charset="UTF-8">
					<input type="hidden" name="_method" value="PUT" />
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<label for="good_id">ID</label>
					<input type="text" name="good_id" disabled="true" value="{{$good->good_id}}"></input>
					<label for="good_advert">Рекламодатель</label>
					<select name='good_advert'>
						@foreach ($adverts as $advert)
							<option {{ $advert->user_id == $good->good_advert ? 'selected' : '' }} value="{{$advert->user_id}}">{{$advert->user_first_name}} {{$advert->user_last_name}}/{{$advert->user_login}}</option>
						@endforeach
					</select>
					<label for="good_name">Название</label>
					<input type="text" name="good_name" value="{{$good->good_name}}"></input>
					<label for="good_price">Цена</label>
					<input type="text" name="good_price" value="{{$good->good_price}}"></input>
					<input type="submit" value="Сохранить"></input>
				</form>
			</div>
        </div>
    </div>
</div>
@endsection

resources/views/goods.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
	            <label for="paginate"> Показывать по</label>
	            <select name="paginate">
	            	<option value="1">1</option>
	            	<option value="2" selected>2</option>
	            	<option value="3">3</option>
	            	<option value="10">10</option>
	            </select>
	            <div id="update">
	            	<table class="table">
					  <thead>
					    <tr>
					    	<th></th>
					      	<th data-order-name="good_id" data-order-direction="asc">#<i class="fa fa-sort active" aria-hidden="true"></i></th>
					      	<th data-order-name="good_name" data-order-direction="asc">Название<i class="fa fa-sort" aria-hidden="true"></i></th>
					      	<th data-order-name="order_client_phone" data-order-direction="asc">Цена<i class="fa fa-sort" aria-hidden="true"></i></th>
					      	<th data-order-name="order_good" data-order-direction="asc">Рекламодатель<i class="fa fa-sort" aria-hidden="true"></i></th>
					    </tr>
					  </thead>
					  <tbody>
						  @foreach ($goods as $index=>$good)
						    <tr>
						    	<td><input name ="good_select[]" type="checkbox" value="{{$good->good_id}}"></td>
						      	<td scope="row">{{$index+1}}</td>
						      	<td><a href="{{ route('good.edit', $good->good_id) }}">{{$good->good_name}}</a> <br> Внешний ID:{{$good->good_id}}</td>
						      	<td>{{$good->good_price}}</td>
						      	<td>{{$good->advert->user_first_name}} {{$good->advert->user_last_name}}<br>{{$good->advert->user_login}})</td>
						    </tr>
						   @endforeach
					  </tbody>
					</table>
					{!! $goods->render() !!}
	            </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }
        .fa.fa-sort {
            float: left;
            color: #bbb;
            padding-top:3px;
        }
        .fa.fa-sort.active{
            color: #337ab7;
        }
        .fa-btn {
            margin-right: 6px;
        }
        th {
            cursor: pointer;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/good') }}">Товары</a></li>
                    <li><a href="{{ url('/order') }}">Заказы</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src='/assets/scripts.js'></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/orders.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
        	<form method="get" name="filter">
        		<label for="date_from"> C </label>
        		<input type="date" name="date_from">
	            <label for="date_to"> По</label>
	            <input type="date" name="date_to">
	            <label for="order_state"> Статус</label>
	            <select name="order_state">
	            	<option value="">Все</option>
	            	@foreach ($states as $state)
	            		<option value="{{$state->state_id}}">{{$state->state_name}}</option>
	            	@endforeach
	            </select>
	            <label for="order_client_phone"> Телефон</label>
	            <input type="text" name="order_client_phone"></input>
	            <label for="order_good"> Товар</label>
	            <input type="text" name="order_good"></input>
	            <label for="order_id"> ID заказа</label>
	            <input type="text" name="order_id"></input>

        	</form>
        	<label for="find"> Поиск</label>
        	<input type="text" name="find">
            <div class="panel panel-default">
	            <label for="paginate"> Показывать по</label>
	            <select name="paginate">
	            	<option value="1">1</option>
	            	<option value="2" selected>2</option>
	            	<option value="3">3</option>
	            	<option value="10">10</option>
	            </select>
	            <div id="update">
	            	<table class="table">
					  <thead>
					    <tr>
					      <th data-order-name="order_id" data-order-direction="asc">#<i class="fa fa-sort active" aria-hidden="true"></i></th>
					      <th data-order-name="order_client_name" data-order-direction="asc">Клиент<i class="fa fa-sort" aria-hidden="true"></i></th>
					      <th data-order-name="order_client_phone" data-order-direction="asc">Телефон<i class="fa fa-sort" aria-hidden="true"></i></th>
					      <th data-order-name="order_good" data-order-direction="asc">Товар<i class="fa fa-sort" aria-hidden="true"></i></th>
					      <th data-order-name="order_state" data-order-direction="asc">Статус<i class="fa fa-sort" aria-hidden="true"></i></th>
					    </tr>
					  </thead>
					  <tbody>
						  @foreach ($orders as $order)
						    <tr>
						      <td>{{$order->order_id}}</td>
						      <td>{{$order->order_client_name}}</td>
						      <td>{{$order->order_client_phone}}</td>
						      <td>{{$order->good->good_name}}<br>{{$order->good->advert->user_first_name}} {{$order->good->advert->user_last_name}} ({{$order->good->advert->user_login}})</td>
						      <td>{{$order->state->state_name}}</td>
						    </tr>
						   @endforeach
					  </tbody>
					</table>
					{!! $orders->render() !!}
	            </div>
            </div>
        </div>
    </div>
</div>
@endsection